### ISSUE TITLE
The Preferences dialog for Fan chart is empty

### ISSUE THREAD

**Issue by elnigno** [gramps-project/gramps-web#434]
The Preferences dialog for Fan chart is empty, it only shows the Reset and Done button, but no option to, for instance, select the number of displayed generations.

![gramps1](https://github.com/gramps-project/gramps-web/assets/2082130/6a9baf8e-e5e4-4450-bc07-d015c5ad11be)
![gramps2](https://github.com/gramps-project/gramps-web/assets/2082130/ce3a7bf3-6ee5-45d3-b6c9-d1bf08dd1931)

System information:
- Gramps 5.2.0
- Gramps Web API 2.1.0
- Gramps Web Frontend 24.3.2
- locale: en
- multi-tree: false
- task queue: true

**Comment by lbprinzr** [comment]
I face the same issue, in addition my fan chart doesn‘t even show up. (Mac, iOS, safari). It worked with v23.x but since v24.1… it stopped working at all.

Gramps 5.2.2
Gramps Web API 2.2.0
Gramps Web Frontend 24.4.0
locale: en
multi-tree: false
task queue: true

I thought it could be data related but, DB check and repair says: No errors were found: the database has passed internal checks.
Finally no errors which could be related to that are shown. Maybe with a hint I could increase loglevel to find some errors somewhere.

**Comment by DavidMStraub** [comment]
Anything in the browser console?

**Comment by lbprinzr** [comment]
Nothing special, I see the request to people api but even with status 200 ok and response 200 ok. The request took 140ms. Preview in browser console shows also content but not chart. If I click preference it‘s empty but there is nothing in the browser console.
i.e. the new relationship graph is working
