### ISSUE TITLE
Editing Notes: html/css can't be edited or deleted

### ISSUE THREAD

**Issue by Naeit** [gramps-project/gramps-web#490]
Hi, I accidentally pasted a piece of css code into the Edit field. Now I cannot delete it.

![IMG_20240829_081129.jpg](https://github.com/user-attachments/assets/9c79b88a-694c-47fa-a28b-d7557284fc48)

![IMG_20240829_081146.jpg](https://github.com/user-attachments/assets/b6bcd5ad-2760-48d2-b5ca-03e20400d30a)

---------------------------------
Gramps 5.2.2
Gramps Web API 2.4.2
Gramps Web Frontend 24.7.1
Gramps QL 0.3.0
locale: en
multi-tree: true
task queue: true

I use Gramps Web via https://grampshub.com

And I use the German interface language.

**Comment by DavidMStraub** [comment]
This is now fixed by stripping HTML tags from pasted tags. For your existing note, the easiest solution is to delete and recreate it once the new version is live on your server.

**Comment by dror3go** [comment]
Still reproducible in the latest version - I wanted to add an HTML element to my note, but failed to do so due to this fix - however in reality the note includes some unwanted chars at the end (which were partially trimmed automatically):

```
<d</<d<d<d 
```

Why stripping HTML tags instead of encoding them? Stripping is complex since it requires analyzing the content, while encoding is "stupid".

**Comment by DavidMStraub** [comment]
This is unrelated to this old issue.

The Gramps Web note editor does not support HTML code. It is based on Gramps styled text (a Gramps internal richt text format).
